// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"test/controllers"
	"test/usecases"
)

// Injectors from wire.go:

func InitializeApp() *App {
	httpClient := NewHttpClient()
	pingUseCase := usecases.NewPingUseCase(httpClient)
	pingController := controllers.NewPingController(pingUseCase)
	app := NewApp(pingController)
	return app
}
